files/urls.py
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    path('', views.index, name='index'),
    path('uploadFile', views.uploadFile, name='uploadFile'),
    path('confirm', views.confirm, name='confirm'),
]

items/urls.py
from django.urls import path

from . import views

app_name = 'items'
urlpatterns = [
    path('', views.index, name='index'),
    path('raidView/<str:raidDate>/', views.raidView, name='raidView'),
    path('<str:itemName>/', views.detail, name='detail'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'mysite'

urlpatterns = [
    path('', views.index, name='index'),
    path('players/', include('players.urls')),
    path('files/', include('files.urls')),
    path('items/', include('items.urls')),
    path('admin/', admin.site.urls),
    path('raids/', include('raids.urls'))
]

players/urls.py
from django.urls import path

from . import views

app_name = 'players'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:playerName>/', views.detail, name='detail'),
]

players/models.py
from django.db import models
from datetime import *


class Player(models.Model):
    playerName = models.CharField('Name', blank=False, max_length=20)
    playerClass = models.CharField('Class', blank=False, max_length=20)
    playerType = models.CharField('Type', blank=False, max_length=20)
    currentDKP = models.IntegerField('DKP', default=0)
    monthPercent = models.DecimalField('30Day', default = 0.00, decimal_places=2, max_digits=5)
    lifePercent = models.DecimalField('Lifetime', default = 0.00, decimal_places=2, max_digits=5)
    checksAvail = models.IntegerField('Possible', default = 0)
    checksEarned = models.IntegerField('Earned', default = 0)
    def __str__(self):
        return self.playerName

class Item(models.Model):
    itemName = models.CharField('Name', blank=False, max_length=50)
    winner = models.CharField('Winner', default='NA', max_length=20)
    price = models.IntegerField(default=0)
    itemDate = models.DateField('Date', default=datetime.now())
    def __str__(self):
        return self.itemName

class File(models.Model):
    fileType = models.CharField('Type', blank=False, max_length=20)
    fileDate = models.DateField('Date', default=datetime.now())
    admin = models.CharField(blank=False, max_length=20)
    def __str__(self):
        return self.fileType + ' - ' + self.fileDate

players/views.py
from django.http.response import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.views import generic
from .models import Player, Item, File
from django.db.models import Q


#Landing page - displays all non alt characters above the guild parse min level
def index(request):
    players_list = Player.objects.filter(~Q(playerType='Alt')).order_by('playerName')
    context = {'player_list': players_list}
    return render(request, 'players/index.html', context)

#Detail page for the player
def detail(request, playerName):
    player = get_object_or_404(Player, playerName=playerName)
    items = Item.objects.filter(Q(winner=playerName)).order_by('-itemDate')
    return render(request, 'players/detail.html', {'player': player, 'items' : items})

# Create your views here.

players/templates/players/detail.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

{% load static %}
<link rel="stylesheet" href="{% static 'players/index.css' %}">

<h1>{{ player.playerName }}</h1>

<fieldset>
    
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <h2>Item History</h2>
    <a class="btn btn-info btn-lg " href="{% url 'players:index'%}" role="button">Back</a>
    <table class="table table-dark">
        <tr>
            <th scope="col">Item Name</th>
            <th scope="col">DKP Spent</th>
            <th scope="col">Date Won</th>
        </tr>
    {% for item in items %}
        <tr><td><a href="{% url 'items:detail' item.itemName %}">{{ item.itemName }}</a></td><td>{{ item.price }}</td><td><a href="{% url 'items:raidView' item.itemDate %}">{{ item.itemDate }}</a></td></tr>
    {% endfor %}
    </table>
</fieldset>
<a class="btn btn-info btn-lg " href="{% url 'players:index'%}" role="button">Back</a>

players/templates/players/index.html
<link rel="stylesheet" link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

{% load static %}
<link rel="stylesheet" href="{% static 'players/index.css' %}">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">DKP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/players">Players</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/items">Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/raids">Raids</a>
        </li>
      </ul>
    </div>
  </nav>

<h1>Players Overview</h1>
<a class="btn btn-info btn-lg " href="{% url 'index'%}" role="button">Back</a>

{% if player_list %}
    <table class="table table-dark">
        <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Current DKP</th>
              <th scope="col">Attendance Checks</th>
            </tr>
          </thead>
    {% for player in player_list %}
        <tr><td><a href="{% url 'players:detail' player.playerName %}">{{ player.playerName }}</a></td><td>{{ player.currentDKP}}</td><td>{{ player.checksEarned }}{{'/'}} {{ player.checksAvail }}</td></tr>
    {% endfor %}
    </table>
{% else %}
    <p>No players are available.</p>
{% endif %}
<a class="btn btn-info btn-lg " href="{% url 'index'%}" role="button">Back</a>