files/urls.py
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    path('', views.index, name='index'),
    path('uploadFile', views.uploadFile, name='uploadFile'),
    path('confirm', views.confirm, name='confirm'),
]

items/urls.py
from django.urls import path

from . import views

app_name = 'items'
urlpatterns = [
    path('', views.index, name='index'),
    path('raidView/<str:raidDate>/', views.raidView, name='raidView'),
    path('<str:itemName>/', views.detail, name='detail'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'mysite'

urlpatterns = [
    path('', views.index, name='index'),
    path('players/', include('players.urls')),
    path('files/', include('files.urls')),
    path('items/', include('items.urls')),
    path('admin/', admin.site.urls),
    path('raids/', include('raids.urls'))
]

players/urls.py
from django.urls import path

from . import views

app_name = 'players'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:playerName>/', views.detail, name='detail'),
]

mysite/views.py
from django.http.response import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from players.models import Player
from players.models import Item
from players.models import File

def index(request):
    return render(request, 'index.html')

mysite/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>DKP Landing</title>
<!-- CSS only -->
  <link rel="stylesheet" link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    {% load static %}
  <link rel="stylesheet" href="{% static 'mysite/index.css' %}">
  </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">DKP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/players">Players</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/items">Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/raids">Raids</a>
        </li>
      </ul>
    </div>
  </nav>
  
  <body>
    <div class="top">
        <h1>Welcome to the DKP Site!</h1>
    </div>

    <a class="btn btn-info btn-lg " href="{% url 'players:index'%}" role="button">Players</a>
    <a class="btn btn-info btn-lg " href="{% url 'items:index'%}" role="button">Items</a>
    <a class="btn btn-info btn-lg " href="{% url 'files:index'%}" role="button">Files</a>
    
  </body>
</html>
