files/urls.py
from django.urls import path

from . import views

app_name = 'files'
urlpatterns = [
    path('', views.index, name='index'),
    path('uploadFile', views.uploadFile, name='uploadFile'),
    path('confirm', views.confirm, name='confirm'),
]

items/urls.py
from django.urls import path

from . import views

app_name = 'items'
urlpatterns = [
    path('', views.index, name='index'),
    path('raidView/<str:raidDate>/', views.raidView, name='raidView'),
    path('<str:itemName>/', views.detail, name='detail'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'mysite'

urlpatterns = [
    path('', views.index, name='index'),
    path('players/', include('players.urls')),
    path('files/', include('files.urls')),
    path('items/', include('items.urls')),
    path('admin/', admin.site.urls),
    path('raids/', include('raids.urls'))
]

players/urls.py
from django.urls import path

from . import views

app_name = 'players'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:playerName>/', views.detail, name='detail'),
]

raids/urls.py
from django.urls import path

from . import views

app_name = 'raids'
urlpatterns = [
    path('', views.index, name='index'),
    path('raidView/<str:raidDate>/', views.raidView, name='raidView'),
]

raids/models.py
from django.db import models

# Create your models here.

raids/views.py
from django.http.response import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.views import generic
import logging
from players.models import Player, Item, File


# Create your views here.
def index(request):
    raids = Item.objects.order_by().values('itemDate').distinct()
    return render(request, 'raids/raidSummary.html', {'raids' : raids})

def raidView(request, raidDate):
    items = Item.objects.filter(itemDate=raidDate).order_by('price')
    return render(request, 'raids/raidView.html', {'items' : items, 'date' : raidDate})


raids/templates/raids/raidSummary.html
<link rel="stylesheet" link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

{% load static %}
<link rel="stylesheet" href="{% static 'players/index.css' %}">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">DKP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/players">Players</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/items">Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/raids">Raids</a>
        </li>
      </ul>
    </div>
  </nav>

  <h1>List of Raids by Date</h1>
  <table class="table table-dark">
{% for raid in raids %}
    <tr><td><a href="{% url 'raids:raidView' raid.itemDate %}">{{ raid.itemDate }}</a></td></tr>
{% endfor %}
</table>

raids/templates/raids/raidView.html
<link rel="stylesheet" link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

{% load static %}
<link rel="stylesheet" href="{% static 'items/index.css' %}">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">DKP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/players">Players</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/items">Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/raids">Raids</a>
        </li>
      </ul>
    </div>
  </nav>

<h1>{{ date }}</h1>

<fieldset>
    
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <h2>Raid Overview</h2>
    <a class="btn btn-info btn-lg " href="{% url 'raids:index'%}" role="button">Back</a>
    <table class="table table-dark">
        <tr>
            <th scope="col">Buyer Name</th>
            <th scope="col">Item Name</th>
            <th scope="col">DKP Spent</th>
            <th scope="col">Date Won</th>
        </tr>
    {% for item in items %}
        <tr><td><a href="{% url 'players:detail' item.winner %}">{{ item.winner }}</a></td><td><a href="{% url 'items:detail' item.itemName %}">{{ item.itemName }}</a></td><td>{{ item.price }}</td><td>{{ item.itemDate }}</td></tr>
    {% endfor %}
    </table>
</fieldset>
<a class="btn btn-info btn-lg " href="{% url 'raids:index'%}" role="button">Back</a>